# Generated by Django 6.0.2 on 2026-02-12 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS users CASCADE;",
            reverse_sql="-- Не поддерживается",
        ),
    ]
