# Generated by Django 6.0.2 on 2026-02-16 08:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Завершен')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Статус происшествия',
                'verbose_name_plural': 'Статусы происшествий',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('severity_level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Уровень серьезности')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Тип происшествия',
                'verbose_name_plural': 'Типы происшествий',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incident_number', models.CharField(max_length=50, unique=True, verbose_name='Номер')),
                ('description', models.TextField(verbose_name='Описание')),
                ('measures_taken', models.TextField(blank=True, verbose_name='Принятые меры')),
                ('responsible_person', models.CharField(blank=True, max_length=100, verbose_name='Ответственное лицо')),
                ('incident_date', models.DateField(verbose_name='Дата происшествия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('incident_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость ущерба')),
                ('downtime_hours', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Часы простоя')),
                ('affected_employees', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Пострадавшие сотрудники')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='users.department', verbose_name='Подразделение')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='incidents.incidentstatus', verbose_name='Статус')),
                ('incident_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='incidents.incidenttype', verbose_name='Тип происшествия')),
            ],
            options={
                'verbose_name': 'Происшествие',
                'verbose_name_plural': 'Происшествия',
                'ordering': ['-incident_date', '-created_at'],
                'permissions': [('view_all_incidents', 'Может просматривать все происшествия'), ('export_incidents', 'Может экспортировать происшествия')],
            },
        ),
        migrations.CreateModel(
            name='IncidentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='incidents/%Y/%m/%d/', verbose_name='Файл')),
                ('file_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='Размер файла (байт)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='incidents.incident', verbose_name='Происшествие')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата комментария')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='incidents.incident', verbose_name='Происшествие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['incident_number'], name='incidents_i_inciden_40c621_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['incident_date'], name='incidents_i_inciden_663685_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['author'], name='incidents_i_author__0dab4d_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['department'], name='incidents_i_departm_8e7f1d_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status'], name='incidents_i_status__0a6426_idx'),
        ),
    ]
