# Generated by Django 6.0.2 on 2026-02-19 06:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidenttype',
            name='color',
            field=models.CharField(default='#3B82F6', max_length=7, validators=[django.core.validators.RegexValidator(message='Введите цвет в формате #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Цвет отображения'),
        ),
    ]
